# Operations on NumPy

### Baics mathematical operations
All mathematical operators with scalar operates elementwise

In [ ]:
# scalar addition
import numpy as np
a = np.arange(10)

# L = [1,2,3]
# Lst = [i+1 for i in L]
# print(Lst)

print(a)
aPlusOne = a + 21 # scalar 1 is added to each element of array
print(aPlusOne)

aPowerTwo = a**2
print(aPowerTwo)

aDivTwo = a//2
print(aDivTwo)

[0 1 2 3 4 5 6 7 8 9]
[21 22 23 24 25 26 27 28 29 30]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 1 1 2 2 3 3 4 4]


In [ ]:
a = np.array([ [1,2,3], [4,5,6] ])
aPowerTwo = a**2
print(aPowerTwo)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
L1 = [1,2,3]
L2 = [3,2,1]
L3 = []
for i in range(len(L1)):
  L3.append(L1[i]-L2[i])
print(L3)

[-2, 0, 2]


In [ ]:
L3 = [L1[i]- L2[i] for i in range(len(L1))]
print(L3)

[-2, 0, 2]


In [ ]:
a = np.array([1,2,3])
b = np.array([3,2,1])
print("subtraction   : ",np.subtract(a,b)) # a - b
print("Addition      : ",np.add(a,b)) # a + b
print("Division      : ",np.divide(a,b)) # a / b element wise
print("Multiplication: ",np.multiply(a,b)) # a * b element wise

subtraction   :  [-2  0  2]
Addition      :  [4 4 4]
Division      :  [0.33333333 1.         3.        ]
Multiplication:  [3 4 3]


In [ ]:
b = np.ones((3,3))
print(b)
b = b + np.array([2,2,2,2])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


ValueError: ignored

In [ ]:
# Multiplication of arrays

A = np.diag([1,2,3,4])
B = np.diag([2,2,2,2])
print(A)
print('\n')
print(B)
print('\n')

C = A*B # This is a element wise matrix matrix Multiplication
print(C)
print('\n')
D = A.dot(B) # This is matrix-matrix multiplication
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


### Comparison
1. Elementwise: compares elementwise and returns boolean value
2. arraywise: checks whether two arrays similar or not and return True or False

In [ ]:
# Elementwise
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
print(a == b)

L = (a == b) # this returns boolean values as array that holds True or False based on comparison
print(L)
print(type(L))

[False  True False  True]
[False  True False  True]
<class 'numpy.ndarray'>


In [ ]:
 a <= b

array([ True,  True, False,  True])

In [ ]:
# Arraywise
print(np.array_equal(a,b)) # if both are same returns True else False
print(np.array_equal(a,a))

False
True


### Logical Operations

In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

OR  = np.logical_or(a, b) # performs elementwise logical OR operation
AND = np.logical_and(a,b) # performs elementwise logical AND operation
XOR = np.logical_xor(a,b) # performs elementwise logical XOR operation
NOT = np.logical_not(a)   # performs elementwise logical XOR operation

print("      a : ",a)
print("      b : ",b)
print('\n')

print(" a OR b : ",OR)
print("a AND b : ",AND)
print("a XOR b : ",XOR)
print("     !a : ",NOT)


      a :  [ True  True False False]
      b :  [ True False  True False]


 a OR b :  [ True  True  True False]
a AND b :  [ True False False False]
a XOR b :  [False  True  True False]
     !a :  [False False  True  True]


In [ ]:
import numpy as np
check = np.all([True, False, -21]) # Check whether all emements are True or nonzero
print(check) # True, 1, Non zer

# check = np.all([True, 1, True]) # Check whether all emements are True or nonzero
# print(check)

check = np.all([2, False, -1]) # Check whether all emements are True or nonzero
print(check)

check = np.all([]) # Check whether all emements are True or nonzero
print(check)

string = "#$^&"
print(string)

False
False
True
#$^&


In [ ]:

check = np.any([True, 1, True]) # Check whether any one emements are True or nonzero
print(check)


check = np.any([True, 2.0, True]) # Check whether all emements are True or nonzero
print(check)

check = np.any([]) # Check whether all emements are True or nonzero
print(check)

True
True
False


In [ ]:
#Note: can be used for array comparisions
a = np.zeros((2, 2))
a[0][0] = 9
print(a)
np.all(a != 0)

[[9. 0.]
 [0. 0.]]


False

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

### Transcendental Operations

In [ ]:
a = np.arange(5)
print(a)
c = np.sin(a)   
print(c)

[0 1 2 3 4]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
np.log(a)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a)   #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape mismatch

In [ ]:
a = np.arange(4)
print(a.shape)
a + np.array([1])

(4,)


array([1, 2, 3, 4])

### Basic Reductions
1. Reduction operation combines all elements of an array by applying specified operation to a single value

In [ ]:
a = np.array([5,-1,43,98])
print("a: ",a)

reduceSum = np.sum(a) # reduction using + operator
print("Sum of array: ",reduceSum)

reduceMin = np.min(a) # reduction using + operator
print("Min of array: ",reduceMin)

reduceMax = np.max(a) # reduction using + operator
print("Max of array: ",reduceMax)

print(type(reduceSum))

a:  [ 5 -1 43 98]
Sum of array:  145
Min of array:  -1
Max of array:  98
<class 'numpy.int64'>


#### sum can also performed on two arrays Note the difference

In [ ]:
a = np.array([1,2,3])
b = np.array([5,5,5])

print(np.sum([a,b]))

print(np.sum([a,b],axis = 0)) # Row wise sum
print(np.sum([a,b],axis = 1)) # Column wise sum

21
[6 7 8]
[ 6 15]


#### dimensionwise reductions

In [ ]:
x = np.array([[1,2], [1,3], [1,1]])
print(x)
print(x.shape)
csum = x.sum(axis=0) # reduction along 1st dimension i.e. columnwise sum of all elements
rsum = x.sum(axis=1) # reduction along 2nd dimension i.e. rowwise sum of all elements
print("rsum: ",rsum)
print("csum: ",csum)

[[1 2]
 [1 3]
 [1 1]]
(3, 2)
rsum:  9
csum:  9


###  Statistics Related Operations on arrays

### Mean

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(x.mean()) # mean of all 4 elements
print(type(x.mean()))

print(y.mean()) # mean of all 6 elements
print(type(y.mean()))

print(np.mean(y,axis = 0)) # mean of all 3 elements in each row 
print(type(np.mean(y,axis = 0))) # note the return type is numpy.ndarray

print(np.mean(y,axis = 1)) # mean of all 3 elements in each row 
print("\n ",type(np.mean(y,axis = 1))) # note the return type is numpy.ndarray

1.75
<class 'numpy.float64'>
3.0
<class 'numpy.float64'>
[3. 4. 2.]
<class 'numpy.ndarray'>
[2. 4.]

  <class 'numpy.ndarray'>


### Standard deviation

In [ ]:
print(x.std())

0.82915619758885


In [ ]:
import numpy as np
idata = np.loadtxt('populations.txt')
print(idata)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [ ]:
year, hares, lynxes, carrots = idata.T #columns to variables
#print(idata.T)
print(hares)

[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


In [ ]:
population = idata[: , 1:] # [:,1:] all entries in first dimension i.e. number of rows, all columns indexed from 1
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [ ]:
popMean = np.mean(population, axis = 0) # mean of hare, lynx, carrots
print(popMean)
# What is mean of hare, lynx, carrots every year?

[27433.33333333 33833.33333333 40500.         50266.66666667
 45433.33333333 34033.33333333 25233.33333333 25566.66666667
 24933.33333333 25533.33333333 26833.33333333 31700.
 37700.         45666.66666667 45800.         36533.33333333
 25866.66666667 21733.33333333 22533.33333333 22533.33333333
 26866.66666667]


In [ ]:
popStd = np.std(population, axis = 0)
print(popStd)

[20897.90645809 16254.59153691  3322.50622558]


In [ ]:
#which species has the highest population each year?
a = np.argmax(population[:,1 ]) # This returns column index of maximum element
print(a)
idata[a][0]


4


1904.0

## Broadcasting

1. Basic operations on numpy arrays (addition, etc.) are elementwise
2. This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.
3. The image below gives an example of broadcasting:

In [ ]:
import numpy as np
A = np.tile(np.arange(0,50,10),(3,1)) # (3,1) states create 3 copise of np.arange() in rows
                                     #  1 says replicate these copies once in columns
A 

array([[ 0, 10, 20, 30, 40],
       [ 0, 10, 20, 30, 40],
       [ 0, 10, 20, 30, 40]])

In [ ]:
np.arange(0,50,10)

array([ 0, 10, 20, 30, 40])

In [ ]:
B = np.array([1,2,3,4,5],)
print(B)

[1 2 3 4 5]


In [ ]:
C = A + B
print(C)

[[ 1 12 23 34 45]
 [ 1 12 23 34 45]
 [ 1 12 23 34 45]]


If you observe [1,2,3,4,5] row is replicated(broadcasted) 3 times as rows to create a matrix of size 3x4
then added with matrix A 

In [ ]:
a = np.arange(0,5,1)
a.shape

(5,)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a = a[:,np.newaxis]
a.shape

(5, 1)

In [ ]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
B


array([1, 2, 3, 4, 5])

In [ ]:
a + B #a is 1 D column replicated to convert into 4x5 matrix

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

### Array Shape Manipulation

#### 1. Flattening: Converts higher dimension array into 1D


In [ ]:
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(a)
print(a.shape)
b = a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. 
          #A copy is made only if needed.
print(b)
print(b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
a.T #Transpose


array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [ ]:
a.T.ravel()

array([1, 1, 4, 4, 2, 2, 5, 5, 3, 3, 6, 6])

#### 2. Reshaping: Inverse of flatening i.e. 1D to higher dimensions

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6], [7,8,9], [10,11,12]])
print(a.shape)
print(a)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
b = a.ravel()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
b = a.reshape(2,2,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
b = a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Note and Beware: reshape may also return a copy!:

In [ ]:
b[0][0] = 999
print(a)

[[[999   2   3]
  [  4   5   6]]

 [[  1   2   3]
  [  4   5   6]]]


In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2) # IF we use trnspose then it will not use same copy
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Adding a Dimension

1. Indexing with the np.newaxis object allows us to add an axis to an array
2. newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,
3. 1D array will become 2D array
4. 2D array will become 3D array
5. 3D array will become 4D array and so on


In [10]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [11]:
x = z[:,np.newaxis]
print(x.shape)
print(x)

(3, 1)
[[1]
 [2]
 [3]]


In [ ]:
y = x[:,np.newaxis]
y
print(y.shape)
print(y)

(3, 1, 1)
[[[1]]

 [[2]]

 [[3]]]


#### Dimension Shuffling

In [ ]:
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a.shape)
print(a)

(4, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


#### Resizing

In [ ]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

#### note that array to be resized should not be assigned to another array

In [ ]:
b = a
a.resize((4,)) 

ValueError: cannot resize this array: it does not own its data

#### Sorting data

In [17]:
a = np.arange(10,1,-1)
print(a)
 
a.sort() # in place 
print(a)

[10  9  8  7  6  5  4  3  2]
[ 2  3  4  5  6  7  8  9 10]


In [24]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
b = np.sort(a,axis = 1)
print("\n",b)

[[5 4 6]
 [2 3 2]]

 [[4 5 6]
 [2 2 3]]


In [47]:
#sorting with fancy indexing
a = np.array([[1,4,3,2], [5,8,7,6]])
             #0  1  2  3 

        
j = np.argsort(a) # returns positions of indices after sorting 1 was at 2nd index, 2 was at 3rd index
j                 # 3 was at 1st index and 4 was at 0th index. Sorted array is [1,2,3,4] argsort gives
                  #[2,3,1,0]
j[0]


array([0, 3, 2, 1])

In [30]:
#j = np.array([3,2,1,0])

In [49]:
print(a[0][j[0]]) # as j is an array with sorted indices
print(a[1][j[1]])

#a[j[0]][j[1]]


[1 2 3 4]
[5 6 7 8]
